// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClwJrNArRPBtxvm3JtCcAmXid_iC6Ooms',
    appId: '1:435202849859:web:e408fc654c7e292dc828f6',
    messagingSenderId: '435202849859',
    projectId: 'notesapp-94a70',
    authDomain: 'notesapp-94a70.firebaseapp.com',
    storageBucket: 'notesapp-94a70.firebasestorage.app',
    measurementId: 'G-ZSFBTPRL3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlVHjHpdu1B9zSEylLGKOw5gl3qyENebo',
    appId: '1:435202849859:android:a881e3f44c4fd1c1c828f6',
    messagingSenderId: '435202849859',
    projectId: 'notesapp-94a70',
    storageBucket: 'notesapp-94a70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjRX9AhljMjKgwOHhEgXwKbvaSQ8M6RhE',
    appId: '1:435202849859:ios:642ad29f7a2fcee5c828f6',
    messagingSenderId: '435202849859',
    projectId: 'notesapp-94a70',
    storageBucket: 'notesapp-94a70.firebasestorage.app',
    iosBundleId: 'com.example.notesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjRX9AhljMjKgwOHhEgXwKbvaSQ8M6RhE',
    appId: '1:435202849859:ios:642ad29f7a2fcee5c828f6',
    messagingSenderId: '435202849859',
    projectId: 'notesapp-94a70',
    storageBucket: 'notesapp-94a70.firebasestorage.app',
    iosBundleId: 'com.example.notesapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClwJrNArRPBtxvm3JtCcAmXid_iC6Ooms',
    appId: '1:435202849859:web:26dcf3ef46e4aeb0c828f6',
    messagingSenderId: '435202849859',
    projectId: 'notesapp-94a70',
    authDomain: 'notesapp-94a70.firebaseapp.com',
    storageBucket: 'notesapp-94a70.firebasestorage.app',
    measurementId: 'G-ESVBM3TNVN',
  );

}